[2024-02-21T07:38:08.945+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-12T00:00:00+00:00 [queued]>
[2024-02-21T07:38:08.957+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-12T00:00:00+00:00 [queued]>
[2024-02-21T07:38:08.957+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T07:38:08.968+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-12 00:00:00+00:00
[2024-02-21T07:38:08.972+0000] {standard_task_runner.py:60} INFO - Started process 116 to run task
[2024-02-21T07:38:08.975+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-12T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpwxlwtuh1']
[2024-02-21T07:38:08.977+0000] {standard_task_runner.py:88} INFO - Job 81: Subtask get_mail
[2024-02-21T07:38:09.012+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-12T00:00:00+00:00 [running]> on host 893865381b0d
[2024-02-21T07:38:09.117+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T00:00:00+00:00'
[2024-02-21T07:38:09.118+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 196, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 261, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/_collections_abc.py", line 837, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2024-02-21T07:38:09.138+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240212T000000, start_date=20240221T073808, end_date=20240221T073809
[2024-02-21T07:38:09.163+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 81 for task get_mail (too many values to unpack (expected 2); 116)
[2024-02-21T07:38:09.188+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T07:38:09.275+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T07:59:59.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-12T00:00:00+00:00 [queued]>
[2024-02-21T07:59:59.120+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-12T00:00:00+00:00 [queued]>
[2024-02-21T07:59:59.120+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T07:59:59.129+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-12 00:00:00+00:00
[2024-02-21T07:59:59.135+0000] {standard_task_runner.py:60} INFO - Started process 390 to run task
[2024-02-21T07:59:59.138+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-12T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmphdn7tkks']
[2024-02-21T07:59:59.140+0000] {standard_task_runner.py:88} INFO - Job 139: Subtask get_mail
[2024-02-21T07:59:59.176+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-12T00:00:00+00:00 [running]> on host 9bab6a0db245
[2024-02-21T07:59:59.239+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T00:00:00+00:00'
[2024-02-21T08:00:02.211+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:00:05.217+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:00:05.219+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-234.txt')
[2024-02-21T08:00:05.219+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.220+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:00:05.221+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-235.txt')
[2024-02-21T08:00:05.221+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.221+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:00:05.222+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-236.txt')
[2024-02-21T08:00:05.223+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.223+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:00:05.224+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-237.txt')
[2024-02-21T08:00:05.224+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.224+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:00:05.225+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-238.txt')
[2024-02-21T08:00:05.225+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.225+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:00:05.226+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-239.txt')
[2024-02-21T08:00:05.226+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.226+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:00:05.227+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-240.txt')
[2024-02-21T08:00:05.227+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.227+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:00:05.229+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-241.txt')
[2024-02-21T08:00:05.229+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.229+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:00:05.230+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-242.txt')
[2024-02-21T08:00:05.230+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.230+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:00:05.231+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-243.txt')
[2024-02-21T08:00:05.231+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:05.854+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:00:05.878+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240212T000000, start_date=20240221T075959, end_date=20240221T080005
[2024-02-21T08:00:05.924+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:00:05.944+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
