[2024-02-21T07:38:09.174+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-02-21T07:38:09.192+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-02-21T07:38:09.192+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T07:38:09.205+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-13 00:00:00+00:00
[2024-02-21T07:38:09.215+0000] {standard_task_runner.py:60} INFO - Started process 117 to run task
[2024-02-21T07:38:09.223+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-13T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpqrydtg66']
[2024-02-21T07:38:09.226+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask get_mail
[2024-02-21T07:38:09.299+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-13T00:00:00+00:00 [running]> on host 893865381b0d
[2024-02-21T07:38:09.455+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T00:00:00+00:00'
[2024-02-21T07:38:09.456+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 196, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 261, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/_collections_abc.py", line 837, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2024-02-21T07:38:09.477+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240213T000000, start_date=20240221T073809, end_date=20240221T073809
[2024-02-21T07:38:09.511+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task get_mail (too many values to unpack (expected 2); 117)
[2024-02-21T07:38:09.562+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T07:38:09.585+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:00:03.657+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-02-21T08:00:03.666+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-02-21T08:00:03.666+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:00:03.678+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-13 00:00:00+00:00
[2024-02-21T08:00:03.684+0000] {standard_task_runner.py:60} INFO - Started process 399 to run task
[2024-02-21T08:00:03.686+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-13T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpom52hvue']
[2024-02-21T08:00:03.688+0000] {standard_task_runner.py:88} INFO - Job 140: Subtask get_mail
[2024-02-21T08:00:03.730+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-13T00:00:00+00:00 [running]> on host 9bab6a0db245
[2024-02-21T08:00:03.793+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T00:00:00+00:00'
[2024-02-21T08:00:06.220+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:00:09.441+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:00:09.443+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-254.txt')
[2024-02-21T08:00:09.443+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.444+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:00:09.445+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-255.txt')
[2024-02-21T08:00:09.445+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.446+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:00:09.447+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-256.txt')
[2024-02-21T08:00:09.447+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.447+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:00:09.449+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-257.txt')
[2024-02-21T08:00:09.449+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.449+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:00:09.451+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-258.txt')
[2024-02-21T08:00:09.451+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.451+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:00:09.453+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-259.txt')
[2024-02-21T08:00:09.453+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.453+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:00:09.454+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-260.txt')
[2024-02-21T08:00:09.455+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.455+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:00:09.456+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-261.txt')
[2024-02-21T08:00:09.456+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.457+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:00:09.458+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-262.txt')
[2024-02-21T08:00:09.458+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:09.459+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:00:09.460+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-263.txt')
[2024-02-21T08:00:09.460+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.052+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:00:10.065+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240213T000000, start_date=20240221T080003, end_date=20240221T080010
[2024-02-21T08:00:10.100+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:00:10.114+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
