[2024-02-21T07:38:17.653+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-02-21T07:38:17.663+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-02-21T07:38:17.663+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T07:38:17.678+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-18 00:00:00+00:00
[2024-02-21T07:38:17.688+0000] {standard_task_runner.py:60} INFO - Started process 129 to run task
[2024-02-21T07:38:17.691+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-18T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmputc9tf3p']
[2024-02-21T07:38:17.693+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask get_mail
[2024-02-21T07:38:17.740+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-18T00:00:00+00:00 [running]> on host 893865381b0d
[2024-02-21T07:38:17.810+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-18T00:00:00+00:00'
[2024-02-21T07:38:17.811+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 196, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 261, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/_collections_abc.py", line 837, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2024-02-21T07:38:17.817+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240218T000000, start_date=20240221T073817, end_date=20240221T073817
[2024-02-21T07:38:17.826+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task get_mail (too many values to unpack (expected 2); 129)
[2024-02-21T07:38:17.863+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T07:38:17.877+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:00:04.425+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-02-21T08:00:04.439+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-18T00:00:00+00:00 [queued]>
[2024-02-21T08:00:04.439+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:00:04.453+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-18 00:00:00+00:00
[2024-02-21T08:00:04.461+0000] {standard_task_runner.py:60} INFO - Started process 401 to run task
[2024-02-21T08:00:04.464+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-18T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpiyt85xt3']
[2024-02-21T08:00:04.466+0000] {standard_task_runner.py:88} INFO - Job 142: Subtask get_mail
[2024-02-21T08:00:04.518+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-18T00:00:00+00:00 [running]> on host 9bab6a0db245
[2024-02-21T08:00:04.598+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-18T00:00:00+00:00'
[2024-02-21T08:00:07.557+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:00:10.605+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:00:10.609+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-292.txt')
[2024-02-21T08:00:10.610+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.610+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:00:10.613+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-293.txt')
[2024-02-21T08:00:10.613+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.614+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:00:10.615+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-294.txt')
[2024-02-21T08:00:10.615+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.615+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:00:10.617+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-295.txt')
[2024-02-21T08:00:10.617+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.617+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:00:10.620+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-296.txt')
[2024-02-21T08:00:10.620+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.620+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:00:10.622+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-297.txt')
[2024-02-21T08:00:10.622+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.622+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:00:10.624+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-298.txt')
[2024-02-21T08:00:10.624+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.624+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:00:10.625+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-299.txt')
[2024-02-21T08:00:10.625+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.625+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:00:10.627+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-300.txt')
[2024-02-21T08:00:10.627+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.627+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:00:10.628+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-301.txt')
[2024-02-21T08:00:10.628+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:11.323+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:00:11.337+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240218T000000, start_date=20240221T080004, end_date=20240221T080011
[2024-02-21T08:00:11.366+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:00:11.381+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
