[2024-02-21T07:38:09.785+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-21T07:38:09.798+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-21T07:38:09.798+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T07:38:09.817+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-15 00:00:00+00:00
[2024-02-21T07:38:09.824+0000] {standard_task_runner.py:60} INFO - Started process 120 to run task
[2024-02-21T07:38:09.827+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-15T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmplj3770my']
[2024-02-21T07:38:09.828+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask get_mail
[2024-02-21T07:38:09.870+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-15T00:00:00+00:00 [running]> on host 893865381b0d
[2024-02-21T07:38:09.978+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-15T00:00:00+00:00'
[2024-02-21T07:38:09.980+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 196, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 261, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/_collections_abc.py", line 837, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2024-02-21T07:38:09.991+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240215T000000, start_date=20240221T073809, end_date=20240221T073809
[2024-02-21T07:38:10.006+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task get_mail (too many values to unpack (expected 2); 120)
[2024-02-21T07:38:10.042+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T07:38:10.066+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:00:04.802+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-21T08:00:04.810+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-15T00:00:00+00:00 [queued]>
[2024-02-21T08:00:04.811+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:00:04.819+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-15 00:00:00+00:00
[2024-02-21T08:00:04.823+0000] {standard_task_runner.py:60} INFO - Started process 403 to run task
[2024-02-21T08:00:04.826+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-15T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpo0i5b8l8']
[2024-02-21T08:00:04.827+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask get_mail
[2024-02-21T08:00:04.860+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-15T00:00:00+00:00 [running]> on host 9bab6a0db245
[2024-02-21T08:00:04.922+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-15T00:00:00+00:00'
[2024-02-21T08:00:07.376+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:00:10.460+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:00:10.466+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-274.txt')
[2024-02-21T08:00:10.467+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.468+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:00:10.473+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-275.txt')
[2024-02-21T08:00:10.474+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.475+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:00:10.480+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-276.txt')
[2024-02-21T08:00:10.480+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.481+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:00:10.486+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-277.txt')
[2024-02-21T08:00:10.486+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.487+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:00:10.490+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-278.txt')
[2024-02-21T08:00:10.490+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.491+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:00:10.493+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-279.txt')
[2024-02-21T08:00:10.494+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.494+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:00:10.496+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-280.txt')
[2024-02-21T08:00:10.496+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.497+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:00:10.499+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-281.txt')
[2024-02-21T08:00:10.499+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.499+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:00:10.501+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-282.txt')
[2024-02-21T08:00:10.501+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.501+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:00:10.503+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-283.txt')
[2024-02-21T08:00:10.503+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:11.114+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:00:11.121+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240215T000000, start_date=20240221T080004, end_date=20240221T080011
[2024-02-21T08:00:11.172+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:00:11.192+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
