[2024-02-21T07:38:17.616+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-17T00:00:00+00:00 [queued]>
[2024-02-21T07:38:17.628+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-17T00:00:00+00:00 [queued]>
[2024-02-21T07:38:17.629+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T07:38:17.644+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-17 00:00:00+00:00
[2024-02-21T07:38:17.650+0000] {standard_task_runner.py:60} INFO - Started process 127 to run task
[2024-02-21T07:38:17.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-17T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmpwhld_z74']
[2024-02-21T07:38:17.654+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask get_mail
[2024-02-21T07:38:17.702+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-17T00:00:00+00:00 [running]> on host 893865381b0d
[2024-02-21T07:38:17.780+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-17T00:00:00+00:00'
[2024-02-21T07:38:17.781+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 196, in execute
    context_merge(context, self.op_kwargs, templates_dict=self.templates_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py", line 261, in context_merge
    context.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/_collections_abc.py", line 837, in update
    for key, value in other:
ValueError: too many values to unpack (expected 2)
[2024-02-21T07:38:17.788+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_email, task_id=get_mail, execution_date=20240217T000000, start_date=20240221T073817, end_date=20240221T073817
[2024-02-21T07:38:17.798+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 88 for task get_mail (too many values to unpack (expected 2); 127)
[2024-02-21T07:38:17.825+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T07:38:17.837+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-21T08:00:04.979+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-17T00:00:00+00:00 [queued]>
[2024-02-21T08:00:04.986+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_email.get_mail scheduled__2024-02-17T00:00:00+00:00 [queued]>
[2024-02-21T08:00:04.986+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-21T08:00:04.995+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_mail> on 2024-02-17 00:00:00+00:00
[2024-02-21T08:00:04.998+0000] {standard_task_runner.py:60} INFO - Started process 405 to run task
[2024-02-21T08:00:05.000+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_email', 'get_mail', 'scheduled__2024-02-17T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/extract_email.py', '--cfg-path', '/tmp/tmph1rgnzhz']
[2024-02-21T08:00:05.002+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask get_mail
[2024-02-21T08:00:05.029+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_email.get_mail scheduled__2024-02-17T00:00:00+00:00 [running]> on host 9bab6a0db245
[2024-02-21T08:00:05.079+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_email' AIRFLOW_CTX_TASK_ID='get_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-17T00:00:00+00:00'
[2024-02-21T08:00:07.557+0000] {ImapSmtp.py:839} INFO - IMAP search: 'gmail:'Message from RPA Python' after:15-12-2023'
[2024-02-21T08:00:10.578+0000] {logging_mixin.py:188} INFO - Message from RPA Python0
[2024-02-21T08:00:10.581+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-284.txt')
[2024-02-21T08:00:10.581+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.582+0000] {logging_mixin.py:188} INFO - Message from RPA Python1
[2024-02-21T08:00:10.584+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-285.txt')
[2024-02-21T08:00:10.585+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.585+0000] {logging_mixin.py:188} INFO - Message from RPA Python2
[2024-02-21T08:00:10.587+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-286.txt')
[2024-02-21T08:00:10.588+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.588+0000] {logging_mixin.py:188} INFO - Message from RPA Python3
[2024-02-21T08:00:10.591+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-287.txt')
[2024-02-21T08:00:10.591+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.591+0000] {logging_mixin.py:188} INFO - Message from RPA Python4
[2024-02-21T08:00:10.594+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-288.txt')
[2024-02-21T08:00:10.594+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.594+0000] {logging_mixin.py:188} INFO - Message from RPA Python5
[2024-02-21T08:00:10.597+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-289.txt')
[2024-02-21T08:00:10.597+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.597+0000] {logging_mixin.py:188} INFO - Message from RPA Python6
[2024-02-21T08:00:10.600+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-290.txt')
[2024-02-21T08:00:10.600+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.600+0000] {logging_mixin.py:188} INFO - Message from RPA Python7
[2024-02-21T08:00:10.604+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-291.txt')
[2024-02-21T08:00:10.604+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.605+0000] {logging_mixin.py:188} INFO - Message from RPA Python8
[2024-02-21T08:00:10.608+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-292.txt')
[2024-02-21T08:00:10.609+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:10.609+0000] {logging_mixin.py:188} INFO - Message from RPA Python9
[2024-02-21T08:00:10.612+0000] {ImapSmtp.py:1240} INFO - Attachment filepath: PosixPath('/data/attachments/test-293.txt')
[2024-02-21T08:00:10.612+0000] {ImapSmtp.py:1243} INFO - Saving attachment: test.txt
[2024-02-21T08:00:11.323+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-21T08:00:11.338+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=extract_email, task_id=get_mail, execution_date=20240217T000000, start_date=20240221T080004, end_date=20240221T080011
[2024-02-21T08:00:11.368+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-21T08:00:11.385+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
